#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (function () {
    $input = new ArgvInput;

    $app = require_once __DIR__.'/bootstrap/app.php';

    /** @var \Illuminate\Foundation\Application $app */
    return $app->handleCommand($input);
})();

exit($status);
